export default {
    UGC: 'https://ugc.svc.halowaypoint.com',
    PACKS: 'https://packs.svc.halowaypoint.com',
    STATS: 'https://stats.svc.halowaypoint.com',
    SPARTAN_STATS: 'https://spartanstats.svc.halowaypoint.com',
    HALO_PLAYER: 'https://haloplayer.svc.halowaypoint.com',
    PRESENCE: 'https://presence.svc.halowaypoint.com',
    TELEMETRY: 'https://telemetry.svc.halowaypoint.com',
    SEARCH: 'https://search.svc.halowaypoint.com',
    CONTENT_HACS: 'https://content-hacs.svc.halowaypoint.com',
    HACS: 'https://hacs.svc.halowaypoint.com',
    ENTITLEMENTS: 'https://entitlements.svc.halowaypoint.com',
    SETTINGS: 'https://settings.svc.halowaypoint.com',
    BANPROCESSOR: 'https://banprocessor.svc.halowaypoint.com',
    CONTENT: 'https://content.halocdn.com',
    CHANNEL: 'https://channel.svc.halowaypoint.com',
    EMBLEM: 'https://emblem.svc.halowaypoint.com',
    LOBBY: 'https://lobby.svc.halowaypoint.com',
    BLOB_CORE: 'https://s3ugc.blob.core.windows.net'
}